### ISSUE TITLE
Suggestion: Seperate Onion class for reusability 

### ISSUE THREAD

**Issue by msamgan** [aldemeery/onion#1]
I would love the ability to create a separate onion class to create a layer sequence with all my actions call one method from that class, and initiate the sequence. 

It is the same as what's happening here but with a class format and accepting action classes (non __invokables.).

let me know what your thoughts are on this.

**Comment by aldemeery** [comment]
@msamgan That sounds cool.

Could you please elaborate? Maybe give an example of what you have in mind?

**Comment by msamgan** [comment]
Thanks for the prompt response. 

let's consider an example of Order placement. 

the following things are to be done once the order is placed. 

1.  Update the system that the order has been placed  
2. Adjust stock
3. Notify the User
4. Notify the Vendor

Now, this can be done via onion in an array. What I am suggesting is something like PlaceOrderOnion, and all we have to do is something like $placeOrderOnion->handle($orderDetails), and this will take the case of all the above steps in the sequence. 

There can be additional functions like skip steps and initial data validation for starting the onion.

**Comment by aldemeery** [comment]
@msamgan You could actually do that without needing to extend the `Onion` class

```php
class PlaceOrder
{
    public function handle(array $orderDetails): void
    {
        onion([
            new AdjustStock(),
            new NotifyTheUser(),
            new NotifyTheVendor(),
        ])->peel($orderDetails);
    }
}
```

Now you can do:

```php
(new PlaceOrder())->handle($orderDetails);
```

**Comment by aldemeery** [comment]
@msamgan

Thank you for your contribution though.

Closing...
